// Generated by https://quicktype.io

export interface Standing {
    points:       Array<number | string>;
    _id:          string;
    pos:          number;
    name:         string;
    team:         string;
    totalPoints:  number;
    seasonPoints: number;
    podiums:      number;
    wins:         number;
    __v:          number;
}

// Generated by https://quicktype.io

export interface UserData {
    name:      string;
    email:     string;
    password:  string;
    password2: string;
    errors:    Errors;
}

export interface Errors {

}

// Generated by https://quicktype.io

export interface Image {
    oldName: string;
    image:   string;
    data:    ImageData;
    user:    ImageUser;
    path?:   string;
}

export interface ImageData {
    likes:        any[];
    dislikes:     any[];
    dateUploaded: number;
    readableDate: string;
    checked:      boolean;
    description:  string;
    followsTheme: boolean;
}

export interface ImageUser {
    name: string;
    uuid: string;
}

// Generated by https://quicktype.io

export interface Haiku {
    haikuLines: string[];
    name:       string;
    url:        string;
    uuid:       string;
}

// Generated by https://quicktype.io

export interface User {
    alerts:       any[];
    uuid:         string;
    verfied:      boolean;
    racerProfile: RacerProfile;
    profile:      Profile;
    roles:        string[];
    email:        string;
    name:         string;
}

export interface Profile {
    theme: string;
}

export interface RacerProfile {
    racerName: string;
    carNumber: number;
    team:      string;
}

export interface Header {
    title: string;
    desc?: string;
    auth: any;
}
